var search={
  "AllenKey Instances Collection": "http://www.github.com/sparqlunicorn#AllenKey_collection",
  "Banana Instances Collection": "http://www.github.com/sparqlunicorn#Banana_collection",
  "Class Instances Collection": "http://www.github.com/sparqlunicorn#Class_collection",
  "Crater Instances Collection": "http://www.github.com/sparqlunicorn#Crater_collection",
  "Cretaceous - High Flatpack / Showroom floruit": "http://www.github.com/sparqlunicorn#nonns_Cretaceous.html",
  "DatatypeProperty Instances Collection": "http://www.github.com/sparqlunicorn#DatatypeProperty_collection",
  "Feature": "http://www.github.com/sparqlunicorn#nonns_Feature.html",
  "FlatpackPanel Instances Collection": "http://www.github.com/sparqlunicorn#FlatpackPanel_collection",
  "Jurassic - Early Flatpack": "http://www.github.com/sparqlunicorn#nonns_Jurassic.html",
  "Kangaroo Instances Collection": "http://www.github.com/sparqlunicorn#Kangaroo_collection",
  "Koetbullar Instances Collection": "http://www.github.com/sparqlunicorn#Koetbullar_collection",
  "LingonberryJar Instances Collection": "http://www.github.com/sparqlunicorn#LingonberryJar_collection",
  "Mesozoic (Age of the Flat-Pack Minions)": "http://www.github.com/sparqlunicorn#nonns_Mesozoic.html",
  "Minion Instances Collection": "http://www.github.com/sparqlunicorn#Minion_collection",
  "Pencil Instances Collection": "http://www.github.com/sparqlunicorn#Pencil_collection",
  "Point Instances Collection": "http://www.github.com/sparqlunicorn#Point_collection",
  "Polygon Instances Collection": "http://www.github.com/sparqlunicorn#Polygon_collection",
  "SP6_Declarative_Place Instances Collection": "http://www.github.com/sparqlunicorn#SP6_Declarative_Place_collection",
  "Stone Instances Collection": "http://www.github.com/sparqlunicorn#Stone_collection",
  "Tealight Instances Collection": "http://www.github.com/sparqlunicorn#Tealight_collection",
  "Trench": "http://www.github.com/sparqlunicorn#nonns_Trench.html",
  "Trench A1": "http://www.github.com/sparqlunicorn#nonns_Trench_A1.html",
  "Trench A2": "http://www.github.com/sparqlunicorn#nonns_Trench_A2.html",
  "Trench A3": "http://www.github.com/sparqlunicorn#nonns_Trench_A3.html",
  "Trench A4": "http://www.github.com/sparqlunicorn#nonns_Trench_A4.html",
  "Trench A5": "http://www.github.com/sparqlunicorn#nonns_Trench_A5.html",
  "Trench A6": "http://www.github.com/sparqlunicorn#nonns_Trench_A6.html",
  "Trench B1": "http://www.github.com/sparqlunicorn#nonns_Trench_B1.html",
  "Trench B2": "http://www.github.com/sparqlunicorn#nonns_Trench_B2.html",
  "Trench B3": "http://www.github.com/sparqlunicorn#nonns_Trench_B3.html",
  "Trench B4": "http://www.github.com/sparqlunicorn#nonns_Trench_B4.html",
  "Trench B5": "http://www.github.com/sparqlunicorn#nonns_Trench_B5.html",
  "Trench B6": "http://www.github.com/sparqlunicorn#nonns_Trench_B6.html",
  "Trench C1": "http://www.github.com/sparqlunicorn#nonns_Trench_C1.html",
  "Trench C2": "http://www.github.com/sparqlunicorn#nonns_Trench_C2.html",
  "Trench C3": "http://www.github.com/sparqlunicorn#nonns_Trench_C3.html",
  "Trench C4": "http://www.github.com/sparqlunicorn#nonns_Trench_C4.html",
  "Trench C5": "http://www.github.com/sparqlunicorn#nonns_Trench_C5.html",
  "Trench C6": "http://www.github.com/sparqlunicorn#nonns_Trench_C6.html",
  "Trench D1": "http://www.github.com/sparqlunicorn#nonns_Trench_D1.html",
  "Trench D2": "http://www.github.com/sparqlunicorn#nonns_Trench_D2.html",
  "Trench D3": "http://www.github.com/sparqlunicorn#nonns_Trench_D3.html",
  "Trench D4": "http://www.github.com/sparqlunicorn#nonns_Trench_D4.html",
  "Trench D5": "http://www.github.com/sparqlunicorn#nonns_Trench_D5.html",
  "Trench D6": "http://www.github.com/sparqlunicorn#nonns_Trench_D6.html",
  "Trench E1": "http://www.github.com/sparqlunicorn#nonns_Trench_E1.html",
  "Trench E2": "http://www.github.com/sparqlunicorn#nonns_Trench_E2.html",
  "Trench E3": "http://www.github.com/sparqlunicorn#nonns_Trench_E3.html",
  "Trench E4": "http://www.github.com/sparqlunicorn#nonns_Trench_E4.html",
  "Trench E5": "http://www.github.com/sparqlunicorn#nonns_Trench_E5.html",
  "Trench E6": "http://www.github.com/sparqlunicorn#nonns_Trench_E6.html",
  "Triassic - Pre-Flatpack": "http://www.github.com/sparqlunicorn#nonns_Triassic.html",
  "condition": "http://www.github.com/sparqlunicorn#Condition",
  "feature id": "http://www.github.com/sparqlunicorn#fid",
  "name": "http://www.github.com/sparqlunicorn#Name",
  "time period (literal)": "http://www.github.com/sparqlunicorn#Time_Period",
  "trench (literal)": "http://www.github.com/sparqlunicorn#Trench"
}